services:
  app:
    container_name: home_lib_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      env_file: ".env"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    # command: "npm run start"
    restart: on-failure

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      # PG_DATA: /var/lib/postgresql/data
      # POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: